-- QUESTION 5 :
DECLARE 

TYPE AVION_RECORD IS RECORD(
    MODELE VARCHAR2(50),
    CAPACITE VARCHAR2(50)
);

AVION AVION_RECORD;

TYPE PASSAGER_RECORD IS RECORD(
    NOM YASSIR.PASSAGER.NOM%TYPE,
    ID YASSIR.PASSAGER.ID_PAS%TYPE
);

PASSAGER PASSAGER_RECORD;

-- TYPE TABLE_AVION IS TABLE OF AVION_RECORD%TYPE;
-- AVIONS TABLE_AVION;

BEGIN

-- QUESTION A : 
UPDATE YASSIR.AVION A
    SET A.CAPACITE=999
    WHERE A.MODELE='A500';
    -- LA VALEUR 3500 PRODUIT UNE ERREUR CAR DANS LA DEFINITION DE LA TABLE LA CAPACITE EST INT(3);
    -- AINSI QUE LE MODELE A400 N'EXISTE PAS

IF SQL%FOUND THEN
        
    SELECT A.MODELE,A.CAPACITE 
        INTO AVION.MODELE, AVION.CAPACITE
        FROM YASSIR.AVION A
        WHERE A.MODELE='A300';

    DBMS_OUTPUT.PUT_LINE('NOM AVION : '
    ||AVION.MODELE
    ||' NOUVELLE CAPACITE : '
    ||AVION.CAPACITE
    );
ELSE
DBMS_OUTPUT.PUT_LINE('RIEN N''A ETE TROUVER ICI');
END IF;

-- QUESTION B :

INSERT INTO YASSIR.PASSAGER(ID_PAS,NOM,AGE,VILLE,HEURE_VOLS)
    VALUES(8,'YASSIR WAHID', 21 , 'CASABLANCA', 5);

IF SQL%FOUND THEN

    SELECT P.ID_PAS,P.NOM 
        INTO PASSAGER.ID,PASSAGER.NOM
        FROM YASSIR.PASSAGER P
        WHERE P.ID_PAS=6;

    DBMS_OUTPUT.PUT_LINE('NOM PASSAGER : '
    ||PASSAGER.NOM
    ||' ID : '
    ||PASSAGER.ID
    );
ELSE
DBMS_OUTPUT.PUT_LINE('RIEN N''A ETE INSERE DANS PASSAGER');
END IF;

-- QUESTION C :

SELECT P.ID_PAS,P.NOM 
    INTO PASSAGER.ID,PASSAGER.NOM
    FROM YASSIR.PASSAGER P
    ORDER BY P.HEURE_VOLS DESC 
    FETCH NEXT 1 ROW ONLY ;

    DBMS_OUTPUT.PUT_LINE('LE PASSAGER AVEC LE PLUS GRAND NOMBRE D''HEURES DE VOYAGES EST : '
    ||PASSAGER.NOM
    ||' ID : '
    ||PASSAGER.ID
    );

END;
/ 