DECLARE
    CURSOR AFFICH_VOLS (
        V_VILLE VOL.VILLE_DEPART%TYPE DEFAULT 'CASABLANCA'
    ) 
    IS
        SELECT *
            FROM YASSIR.VOL
            WHERE VILLE_DEPART=V_VILLE;

BEGIN
    FOR VOL IN AFFICH_VOLS LOOP
        DBMS_OUTPUT.PUT_LINE('NUM DU VOL : ' || VOL.ID_VOL);
        DBMS_OUTPUT.PUT_LINE('DATE DEPART : ' || VOL.DATE_DEPART);
        DBMS_OUTPUT.PUT_LINE('DATE ARRIVEE : ' || VOL.DATE_ARRIVEE);
        DBMS_OUTPUT.PUT_LINE('VILLE DEPART : ' || VOL.VILLE_DEPART);
        DBMS_OUTPUT.PUT_LINE('VILLE ARRIVEE : ' || VOL.VILLE_ARRIVEE);
        DBMS_OUTPUT.PUT_LINE('NUM AVION : ' || VOL.N_AVION);
        DBMS_OUTPUT.PUT_LINE('NUM PILOTE : ' || VOL.N_PILOTE);
        DBMS_OUTPUT.PUT_LINE('----------------------------------------------'); 
    END LOOP;
END;
/