DECLARE
    
    CURSOR AFFICH_VOLS_PILOTE (
        NUM_PILOTE YASSIR.VOL.N_PILOTE%TYPE
    ) 
    IS
        SELECT *
            FROM YASSIR.VOL
            WHERE N_PILOTE=NUM_PILOTE;

    TYPE VOL_PIL_TYPE IS TABLE OF YASSIR.VOL%ROWTYPE;
    VOL_PIL VOL_PIL_TYPE;

    NUM_PILOTE YASSIR.VOL.N_PILOTE%TYPE; 

BEGIN

    NUM_PILOTE := '&NUM_PILOTE' ;

    OPEN AFFICH_VOLS_PILOTE(NUM_PILOTE);
    FETCH AFFICH_VOLS_PILOTE BULK COLLECT INTO VOL_PIL;

    FOR I IN 1..VOL_PIL.COUNT LOOP
            DBMS_OUTPUT.PUT_LINE('NUM DU VOL : ' || VOL_PIL(I).ID_VOL);
            DBMS_OUTPUT.PUT_LINE('DATE DEPART : ' || VOL_PIL(I).DATE_DEPART);
            DBMS_OUTPUT.PUT_LINE('DATE ARRIVEE : ' || VOL_PIL(I).DATE_ARRIVEE);
            DBMS_OUTPUT.PUT_LINE('VILLE DEPART : ' || VOL_PIL(I).VILLE_DEPART);
            DBMS_OUTPUT.PUT_LINE('VILLE ARRIVEE : ' || VOL_PIL(I).VILLE_ARRIVEE);
            DBMS_OUTPUT.PUT_LINE('NUM AVION : ' || VOL_PIL(I).N_AVION);
            DBMS_OUTPUT.PUT_LINE('NUM PILOTE : ' || VOL_PIL(I).N_PILOTE);
            DBMS_OUTPUT.PUT_LINE('----------------------------------------------'); 
    END LOOP;

END;
/