SET SERVEROUTPUT ON;

DECLARE
    CURSOR C_PILOTES IS 
        SELECT * FROM PILOTE 
        WHERE SALAIRE < (SELECT AVG(SALAIRE) FROM PILOTE) FOR UPDATE;

BEGIN

    FOR pilote_rec IN C_PILOTES

    LOOP
        UPDATE PILOTE 
        SET SALAIRE = SALAIRE + SALAIRE * 0.2
        WHERE CURRENT OF C_PILOTES;
    END LOOP;

    

END;
/
