-- QUESTION 3 :

SET SERVEROUTPUT ON;

DECLARE

V_VOL VARCHAR2(8);
V_NUM NUMBER(3);
V_DATE DATE;



BEGIN

V_VOL := '&___INTRODUISEZ_VOTRE_NUMERO_DE_VOL';
V_NUM := '&___INTRODUISEZ_VOTRE_NUMERO_DE_PASSAGER';
V_DATE := TO_DATE('&___INTRODUISEZ_LA_DATE_DE_DEPART_SOUS_CETTE_FORME__AAAA_MM_JJ','YYYY-MM-DD');
DBMS_OUTPUT.PUT_LINE('DATE : '||V_DATE);

IF V_DATE > SYSDATE 
THEN

INSERT INTO RESERVATION(N_VOL,N_PASSAGER,DATE_RES) 
VALUES ( V_VOL,V_NUM,V_DATE);

ELSE

DBMS_OUTPUT.PUT_LINE('DATE INVALID MERCI DE REESSAYEER....');

END IF;


END;
/