CREATE OR REPLACE PROCEDURE PRIME
    (
        TAUX FLOAT IN,
        PILOTE YASSIR.PILOTE.ID_PIL%TYPE,
    )
IS
    taux_invalide EXCEPTION;
    PILOTE_INTROUVALBE EXCEPTION;

    BEGIN 
        IF TAUX < 0 OR TAUX > 0.4 THEN
            RAISE taux_invalide;
        END IF;

        IF PILOTE NOT IN (SELECT ID_PIL FROM YASSIR.PILOTE) THEN
            RAISE PILOTE_INTROUVALBE;
        END IF;

        UPDATE YASSIR.PILOTE SET SALAIRE = SALAIRE + (SALAIRE * TAUX) WHERE ID_PIL = PILOTE;

        EXCEPTIONS
            WHEN taux_invalide THEN
                
                TAUX := 0.4;
                
                UPDATE YASSIR.PILOTE SET SALAIRE = SALAIRE + (SALAIRE * TAUX) WHERE ID_PIL = PILOTE;

                DBMS_OUTPUT.PUT_LINE('LE TAUX QUE VOUS AVEZ SAISSI EST INVALIDE, VEUILLER SAISIR UN TAUX ENTRE 0% ET 40%');
            WHEN PILOTE_INTROUVALBE THEN
                DBMS_OUTPUT.PUT_LINE('PILOTE INTROUVALBE, VEUILLEZ VERIFIEZ UNE AUTRE FOIS QUE L''ID DU PILOTE EST CORRECTE');
