CREATE OR REPLACE TRIGGER limite_affect_vol_pil
BEFORE INSERT OR UPDATE ON YASSIR.vol
FOR EACH ROW
DECLARE
    NB_VOL_PIL NUMBER := 0;
BEGIN
    SELECT COUNT(*) 
    INTO NB_VOL_PIL
    FROM YASSIR.VOL
    WHERE N_PILOTE = :NEW.N_PILOTE
    AND :NEW.DATE_DEPART >= NEXT_DAY(TRUNC(SYSDATE) - 7, 'MONDAY')
    AND :NEW.DATE_DEPART < NEXT_DAY(TRUNC(SYSDATE), 'MONDAY');

    IF NB_VOL_PIL >= 4 THEN

        EXECUTE IMMEDIATE 'CREATE TABLE YASSIR.ARCHIVS_VOL (
            UTILISATEUR VARCHAR2(30),
            DATE DATE,
            ID_PILOTE NUMBER,
            DATE_DEPART DATE)' ;

        INSERT INTO YASSIR.ARCHIVS_VOL (UTILISATEUR, DATE, ID_PILOTE, DATE_DEPART)
        VALUES (USER, SYSDATE, :NEW.N_PILOTE, :NEW.DATE_DEPART);
    END IF;

END;
/

DROP TRIGGER limite_affect_vol_pil;
